name : coupon
channels :
 - anaconda
 - conda-forge
 - defaults 
dependencies:
 - pip=21.1.3
 - python=3.8
 - pycaret=2.3.5
 - numpy=1.19.5
 - pandas=1.1.5
 - seaborn=0.11.2
 - matplotlib=3.3.4
 - scikit-learn=0.23.2
 - mlxtend=0.19.0
 - statsmodels=0.12.2
 - imbalanced-learn=0.7.0
 - lightgbm=3.3.1
 - shap=0.40.0
 - pip:
   - scipy==1.5.4
   - mlflow==1.25.1